### ISSUE TITLE
NXDOMAIN for bentenv.com

### ISSUE THREAD

**Issue by hello-smile6** [bent-env/images#1]

**Comment by hello-smile6** [comment]
@3p3r

**Comment by hello-smile6** [comment]
Still NXDOMAIN

**Comment by 3p3r** [comment]
the domain is just a hobby/idea project of mine. nothing is online yet 👍

**Comment by hello-smile6** [comment]
> the domain is just a hobby/idea project of mine. nothing is online yet 👍

Is there an alternative DNS server I could use for it to work?

**Comment by 3p3r** [comment]
For the images in this repo you mean?
